export const SUPABASE_URL = 'https://kwurnxhbftgaxkbikvdd.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dXJueGhiZnRnYXhrYmlrdmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzMjExMzUsImV4cCI6MjA5Nzg5NzEzNX0.tnrE0u9w0PLS9nJEflMhBGxh3cFhpHyA-Bzln_bVC50';
